### ISSUE TITLE
Peer dependencies with vite v4

### ISSUE THREAD

**Issue by AlexisDoroszkiewicz** [wxsms/vite-plugin-libcss#5]
Hello
There seems to have some peer dependencies issues with the vite v4

`Could not resolve dependency:
npm ERR! peer vite@"^2" from vite-plugin-libcss@1.0.5
npm ERR! node_modules/vite-plugin-libcss
npm ERR!   dev vite-plugin-libcss@"*" from the root project`

**Comment by wxsms** [comment]
fixed by changing peer versin to `*`.
